USE voter_crm;

/*drop table VoterDetails;*/


CREATE TABLE VoterDetails(
      Voter_Details_Id int PRIMARY KEY AUTO_INCREMENT,
      voter_id char(10) UNIQUE NOT NULL	,
      FOREIGN key (voter_id) REFERENCES Voters(Voter_UID),
      voter_name varchar(100) NOT NULL ,
      voter_father_name varchar(100) ,
      address text ,
      street text,
      ward text ,
      phone_number bigint ,
      check (length(phone_number)=10),
      whatsapp_number bigint ,
      check (length(whatsapp_number) = 10),
      voter_gender varchar(25) ,
      voter_marital_status varchar(25) ,
      voter_age int(3) ,
      check (voter_age>=18 and voter_age<=140),
      voter_educational_qualification varchar(25) ,
      voter_profession varchar(25) ,
      voter_income_per_month int ,
      voter_income_per_year int ,
      voter_family_income_per_month int	,
      number_of_votes_in_voters_family int,
      number_of_votes_in_voters_extended_family int,
      voter_caste varchar(25) ,
      voter_political_party varchar(100) ,
      whether_voter_is_politically_neutral varchar(25),
      whether_voter_is_getting_government_benefits varchar(25),
      whether_voters_family_is_getting_government_benefits varchar(25),
      voter_work_location text ,
      whether_voter_accepts_money_from_political_party varchar(25),
      whether_voters_family_accepts_money_from_political_party varchar(25),
      number_of_police_cases_on_voter int	,
      number_of_police_cases_on_voters_family_members int	,
      voter_has_own_house	varchar(25),
      whether_voter_is_migrated_from_another_place varchar(25),
      voter_opinion_on_present_government text,
      opinion_label_on_present_government varchar(25),
      voter_opinion_on_local_MLA text ,
      opinion_label_on_local_MLA varchar(25),
      local_MLA_political_party  varchar(100)	,
      FOREIGN KEY (local_MLA_political_party) REFERENCES PoliticalParties(Party_Name),
      voter_opinion_on_opposition_party_MLA_candidate text,
      opinion_label_on_opposition_party_MLA_candidate  varchar(25),
      opposition_party_MLA_candidate_political_party  varchar(100),
      FOREIGN KEY (opposition_party_MLA_candidate_political_party) REFERENCES PoliticalParties(Party_Name),
      voter_opinion_on_local_coporator_or_village_president text ,
      opinion_label_on_local_coporator_or_village_president	varchar(25) ,
      local_coporator_political_party	varchar(100),
      FOREIGN KEY (local_coporator_political_party) REFERENCES PoliticalParties(Party_Name),
      which_political_party_you_wish_to_vote	varchar(100),
      FOREIGN KEY (which_political_party_you_wish_to_vote) REFERENCES PoliticalParties(Party_Name),
      BPL varchar(25),
      reservation_category varchar(25) ,
      voting_first_time	varchar(25),
      constituency_name varchar(100) ,
      CONSTRAINT FK_constituency FOREIGN KEY (constituency_name) REFERENCES AssemblyConstituency(Constituency_Name),
      polling_booth_name varchar(100)	,
      polling_booth_no int ,
      CONSTRAINT FK_Polling_booth FOREIGN KEY (polling_booth_no, polling_booth_name)
      REFERENCES PollingStations(Polling_Station_No, Polling_Station_Name),
      /*FOREIGN KEY (polling_booth_name) REFERENCES PollingStations(Polling_Station_Name),*/
      pincode int(6),
      check (length(pincode) = 6),
      latitude text	,
      longitude text,
      is_voter_handicap varchar(25)	,
      number_of_members_visited_foreign_country_in_voters_family int ,
      number_of_dependents_of_the_voter int	,
      voter_religion varchar(25),
      voter_has_own_car	varchar(25),
      voter_has_own_bike varchar(25),
      voter_mother_tongue varchar(25),
      voter_monthly_spending int,
      voter_family_monthly_spending int	,
      voted_in_last_election varchar(25)

);

